# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Resolve dependencies
        run: swift package resolve
      - uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          spm-package: .
          scheme: Sequoia
          destination: platform=iOS Simulator,name=iPhone 16
          action: test
