name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2
      - name: Resolve dependencies
        run: swift package resolve
      - uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          spm-package: .
          scheme: Sequoia
          destination: platform=iOS Simulator,name=iPhone 16
          action: test
